### ISSUE TITLE
Directly support flatpakref

### ISSUE THREAD

**Issue by castrojo** [kolunmi/bazaar#121]
This is so awful lol. Can we make it so clicking on a flatpakref just opens bazaar and prompts for installation? 

https://youtu.be/Sa8nMiEoti0?si=vc_PnJe2kRuB19PF&t=949

**Comment by kolunmi** [comment]
yep on it

**Comment by kolunmi** [comment]
done: ef1941862469a0e1bb00348e21403db5220e2ed9

**Comment by XRaTiX** [comment]
Still not open with double click 

https://github.com/kolunmi/bazaar/issues/161
