### ISSUE TITLE
Segmentation fault after loading is finished

### ISSUE THREAD

**Issue by AtiusAmy** [kolunmi/bazaar#148]
Bazaar loads for a bit and when the progress bar is done, it segmentation faults.

Here is the log:
```
atiusamy@bluefin:~$ /usr/bin/bazaar window --auto-service

** (bazaar:8820): CRITICAL **: 15:13:28.007: bz_flathub_state_dup_apps_of_the_week: assertion 'self->initializing == NULL' failed

** (bazaar:8820): CRITICAL **: 15:13:28.007: bz_flathub_state_dup_trending: assertion 'self->initializing == NULL' failed

** (bazaar:8820): CRITICAL **: 15:13:28.007: bz_flathub_state_dup_recently_updated: assertion 'self->initializing == NULL' failed

** (bazaar:8820): CRITICAL **: 15:13:28.007: bz_flathub_state_dup_recently_added: assertion 'self->initializing == NULL' failed

** (bazaar:8820): CRITICAL **: 15:13:28.007: bz_flathub_state_dup_popular: assertion 'self->initializing == NULL' failed

(bazaar:8820): GLib-GObject-CRITICAL **: 15:13:38.156: g_object_add_weak_pointer: assertion 'G_IS_OBJECT (object)' failed

(bazaar:8820): GLib-GObject-CRITICAL **: 15:13:38.157: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault (core dumped)
```

**Comment by lucazade** [comment]
same issue here:

bazzite@192:/var/home/bazzite$ env GSK_RENDERER=opengl bazaar window --auto-service

(bazaar:7793): Gtk-WARNING **: 18:12:17.517: Unknown key gtk-modules in /home/bazzite/.config/gtk-4.0/settings.ini

(bazaar:7793): Adwaita-WARNING **: 18:12:17.812: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

** (bazaar:7793): CRITICAL **: 18:12:18.129: bz_flathub_state_dup_apps_of_the_week: assertion 'self->initializing == NULL' failed

** (bazaar:7793): CRITICAL **: 18:12:18.129: bz_flathub_state_dup_trending: assertion 'self->initializing == NULL' failed

** (bazaar:7793): CRITICAL **: 18:12:18.129: bz_flathub_state_dup_recently_updated: assertion 'self->initializing == NULL' failed

** (bazaar:7793): CRITICAL **: 18:12:18.129: bz_flathub_state_dup_recently_added: assertion 'self->initializing == NULL' failed

** (bazaar:7793): CRITICAL **: 18:12:18.129: bz_flathub_state_dup_popular: assertion 'self->initializing == NULL' failed

(bazaar:7793): Gtk-CRITICAL **: 18:12:21.210: Comparison method violates its general contract

(bazaar:7793): Gtk-CRITICAL **: 18:12:21.457: Comparison method violates its general contract

** (bazaar:7793): CRITICAL **: 18:12:22.737: ID 'com.valvesoftware.Steam' from flathub was not found!

** (bazaar:7793): CRITICAL **: 18:12:22.737: ID 'net.lutris.Lutris' from flathub was not found!
Errore di segmentazione (core dump creato)

**Comment by lrefra** [comment]
Same here:

$ bazaar window --auto-service

(bazaar:22263): Gtk-WARNING **: 13:58:28.246: Unknown key gtk-modules in /home/lrefra/.config/gtk-4.0/settings.ini

(bazaar:22263): Adwaita-WARNING **: 13:58:28.346: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

** (bazaar:22263): CRITICAL **: 13:58:28.471: bz_flathub_state_dup_apps_of_the_week: assertion 'self->initializing == NULL' failed

** (bazaar:22263): CRITICAL **: 13:58:28.471: bz_flathub_state_dup_trending: assertion 'self->initializing == NULL' failed

** (bazaar:22263): CRITICAL **: 13:58:28.471: bz_flathub_state_dup_recently_updated: assertion 'self->initializing == NULL' failed

** (bazaar:22263): CRITICAL **: 13:58:28.471: bz_flathub_state_dup_recently_added: assertion 'self->initializing == NULL' failed

** (bazaar:22263): CRITICAL **: 13:58:28.471: bz_flathub_state_dup_popular: assertion 'self->initializing == NULL' failed
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:940: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:972: FINISHME: support more multi-planar formats with DRM modifiers

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.608: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.614: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.663: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.674: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.716: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.739: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.743: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.783: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.853: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.870: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.894: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.905: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.955: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.964: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.969: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.973: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.981: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:31.996: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.002: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.005: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.057: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.066: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.068: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.101: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.117: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.134: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.188: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.212: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.216: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.289: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.395: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.398: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.447: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.450: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.466: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.484: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.505: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.521: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.530: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.551: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.559: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.579: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.613: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.662: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.766: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.771: Comparison method violates its general contract

(bazaar:22263): Gtk-CRITICAL **: 13:58:32.816: Comparison method violates its general contract

** (bazaar:22263): CRITICAL **: 13:58:33.113: ID 'com.valvesoftware.Steam' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.113: ID 'net.lutris.Lutris' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.PyCharm-Community' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.IntelliJ-IDEA-Community' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.IntelliJ-IDEA-Ultimate' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.PyCharm-Professional' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.Rider' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.CLion' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.WebStorm' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.jetbrains.PhpStorm' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'app.devsuite.Ptyxis' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'org.openrgb.OpenRGB' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'com.valvesoftware.Steam' from flathub was not found!

** (bazaar:22263): CRITICAL **: 13:58:33.134: ID 'net.lutris.Lutris' from flathub was not found!
Violación de segmento (`core' generado)

**Comment by sonicbhoc** [comment]
The same is happening with me.

```
cchristie@DoctorRobotnet:~$ bazaar window --auto-service

(bazaar:65457): Gtk-WARNING **: 15:02:09.251: Unknown key gtk-modules in /home/cchristie/.config/gtk-4.0/settings.ini

(bazaar:65457): Adwaita-WARNING **: 15:02:09.341: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

** (bazaar:65457): CRITICAL **: 15:02:09.463: bz_flathub_state_dup_apps_of_the_week: assertion 'self->initializing == NULL' failed

** (bazaar:65457): CRITICAL **: 15:02:09.463: bz_flathub_state_dup_trending: assertion 'self->initializing == NULL' failed

** (bazaar:65457): CRITICAL **: 15:02:09.463: bz_flathub_state_dup_recently_updated: assertion 'self->initializing == NULL' failed

** (bazaar:65457): CRITICAL **: 15:02:09.463: bz_flathub_state_dup_recently_added: assertion 'self->initializing == NULL' failed

** (bazaar:65457): CRITICAL **: 15:02:09.463: bz_flathub_state_dup_popular: assertion 'self->initializing == NULL' failed

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.184: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.230: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.293: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.409: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.446: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.448: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.520: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.676: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.682: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.689: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.702: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.716: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.720: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.739: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.746: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.747: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.751: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.776: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.782: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.836: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.838: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.841: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.863: Comparison method violates its general contract

(bazaar:65457): Gtk-CRITICAL **: 15:02:12.972: Comparison method violates its general contract

** (bazaar:65457): CRITICAL **: 15:02:14.996: ID 'com.valvesoftware.Steam' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:14.996: ID 'net.lutris.Lutris' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.PyCharm-Community' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.IntelliJ-IDEA-Community' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.IntelliJ-IDEA-Ultimate' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.PyCharm-Professional' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.Rider' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.CLion' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.WebStorm' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.jetbrains.PhpStorm' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'app.devsuite.Ptyxis' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'org.openrgb.OpenRGB' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'com.valvesoftware.Steam' from flathub was not found!

** (bazaar:65457): CRITICAL **: 15:02:15.011: ID 'net.lutris.Lutris' from flathub was not found!
Segmentation fault         (core dumped) bazaar window --auto-service
```

System Details:

```
Operating System: Bazzite 42
KDE Plasma Version: 6.4.2
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.6-101.bazzite.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 16 GiB of RAM (15.5 GiB usable)
Graphics Processor: AMD Radeon RX 6700 XT
```

ostree layer: 48b36b3

**Comment by kolunmi** [comment]
Should be fixed in the latest release, sit tight for bazzite to upgrade

**Comment by lucazade** [comment]
issue still present after latest release

$ rpm -q bazaar
bazaar-0.0.git.958.11f5c582.ea31ad4-3.fc42.x86_64

$ bazaar window --auto-service
(bazaar:3480): Gtk-WARNING **: 09:53:17.856: Unknown key gtk-modules in /home/bazzite/.config/gtk-4.0/settings.ini

(bazaar:3480): Adwaita-WARNING **: 09:53:18.145: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(bazaar:3480): Gtk-CRITICAL **: 09:53:22.050: Comparison method violates its general contract

(bazaar:3480): Gtk-CRITICAL **: 09:53:22.129: Comparison method violates its general contract

(bazaar:3480): Gtk-CRITICAL **: 09:53:22.163: Comparison method violates its general contract

(bazaar:3480): Gtk-CRITICAL **: 09:53:23.016: Comparison method violates its general contract

(bazaar:3480): Gdk-WARNING **: 09:53:23.468: vkCreateSwapchainKHR(): Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED) (-3)

(bazaar:3480): Gdk-WARNING **: 09:53:23.468: Could not create swapchain for this surface: Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED)
Errore di segmentazione (core dump creato)

**Comment by lucazade** [comment]
found the stacktrace, attached log

[stacktrace.txt](https://github.com/user-attachments/files/21260499/stacktrace.txt)

**Comment by kolunmi** [comment]
This is not the same crash, this is a gtk issue which is also being tracked. Try setting `GDK_BACKEND=x11`.

Please do not dump huge logs as regular text, you can upload files

**Comment by lucazade** [comment]
> This is not the same crash, this is a gtk issue which is also being tracked. Try setting `GDK_BACKEND=x11`.
> 
> Please do not dump huge logs as regular text, you can upload files

attached dump, sorry for huge post!
could you please point me out the tracked gtk issue?

**Comment by kolunmi** [comment]
This issue has been fixed by gtk, sorry for not pointing you to the issue when this was filed
