### ISSUE TITLE
App banners missing icons, titles and descriptions

### ISSUE THREAD

**Issue by mcphail** [kolunmi/bazaar#54]
![Image](https://github.com/user-attachments/assets/ddf9ce4f-f803-474d-9ce5-1497ab4ce8bf)

Please see the attached screenshot. GnuIMP and Inkscape are missing titles and description. LibreOffice is missing an icon. Selecting "refresh" does not help to populate them correctly. There are several more apps which show up like this. The banners display correctly in GNOME Software.

Using Bazaar on Bluefin 42.20250622.1

Thanks for your work on this app.

**Comment by kolunmi** [comment]
fixed, thanks for the issue

**Comment by mcphail** [comment]
Hi. The app is still missing descriptions/titles for various apps. See GnuIMP and Inkscape:

<img width="1297" height="446" alt="Image" src="https://github.com/user-attachments/assets/3f4e5a02-f5b2-44ea-a9d2-08105d435a01" />

**Comment by mcphail** [comment]
Running version on current bluefin-stable-dx

<img width="336" height="283" alt="Image" src="https://github.com/user-attachments/assets/8c2c6d91-c999-482e-b29d-11211babf1f6" />
